#!/usr/bin/env python3
"""
Multi-platform deployment script for CrewAI + Ollama.

This script bootstraps a fully self-contained, secure environment that includes:
  - Installation (or upgrade) of Ollama in a sandboxed location
  - Creation of an isolated Python virtual environment
  - Installation of CrewAI application dependencies
  - Installation of the crewctl CLI for agent/model lifecycle management
  - Optional installation of training extras for LoRA/LRM fine-tuning

The script is designed to be idempotent and safe to re-run. All artifacts are
created inside the project directory under `.crewctl/`.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import logging
import os
import platform
import shutil
import stat
import subprocess
import sys
import tarfile
import textwrap
from pathlib import Path
from typing import Dict, Iterable, Optional, Tuple
from urllib.error import HTTPError, URLError
from urllib.request import urlopen
from venv import EnvBuilder


ROOT = Path(__file__).resolve().parents[1]
STATE_DIR = ROOT / ".crewctl"
DOWNLOADS_DIR = STATE_DIR / "downloads"
BIN_DIR = STATE_DIR / "bin"
LOG_DIR = STATE_DIR / "logs"
MODEL_REGISTRY_PATH = ROOT / "config" / "model_registry.json"
ENV_TEMPLATE = ROOT / ".env.template"
ENV_FILE = ROOT / ".env"


class DeployError(RuntimeError):
    """Deployment failure."""


def setup_logging(verbose: bool = False) -> None:
    LOG_DIR.mkdir(parents=True, exist_ok=True)
    log_file = LOG_DIR / "deploy.log"
    handlers = [
        logging.FileHandler(log_file, encoding="utf-8"),
        logging.StreamHandler(sys.stdout),
    ]
    level = logging.DEBUG if verbose else logging.INFO
    logging.basicConfig(
        level=level,
        format="%(asctime)s | %(levelname)-8s | %(message)s",
        handlers=handlers,
    )


def run(
    cmd: Iterable[str],
    *,
    cwd: Optional[Path] = None,
    check: bool = True,
    env: Optional[Dict[str, str]] = None,
) -> subprocess.CompletedProcess:
    cmd_list = list(cmd)
    logging.debug("Executing command: %s", " ".join(cmd_list))
    try:
        result = subprocess.run(
            cmd_list,
            cwd=str(cwd) if cwd else None,
            check=check,
            env=env,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
    except FileNotFoundError as exc:
        raise DeployError(f"Required command not found: {cmd_list[0]}") from exc
    if check and result.returncode != 0:
        raise DeployError(
            f"Command failed ({result.returncode}): {' '.join(cmd_list)}\n"
            f"stdout:\n{result.stdout}\n"
            f"stderr:\n{result.stderr}"
        )
    if result.stdout:
        logging.debug("stdout:\n%s", result.stdout)
    if result.stderr:
        logging.debug("stderr:\n%s", result.stderr)
    return result


def download(url: str, destination: Path, *, expected_sha256: Optional[str] = None) -> Path:
    destination.parent.mkdir(parents=True, exist_ok=True)
    logging.info("Downloading %s -> %s", url, destination)
    try:
        with urlopen(url) as response, destination.open("wb") as f:
            shutil.copyfileobj(response, f)
    except HTTPError as exc:
        raise DeployError(f"Failed to download {url} (HTTP {exc.code})") from exc
    except URLError as exc:
        raise DeployError(f"Failed to download {url}: {exc.reason}") from exc

    if expected_sha256:
        logging.debug("Verifying SHA256 checksum for %s", destination.name)
        actual = sha256sum(destination)
        if actual.lower() != expected_sha256.lower():
            raise DeployError(
                f"Checksum mismatch for {destination.name}.\n"
                f"Expected: {expected_sha256}\n"
                f"Actual:   {actual}"
            )
    return destination


def sha256sum(path: Path) -> str:
    hasher = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            hasher.update(chunk)
    return hasher.hexdigest()


def ensure_model_registry() -> None:
    MODEL_REGISTRY_PATH.parent.mkdir(parents=True, exist_ok=True)
    if not MODEL_REGISTRY_PATH.exists():
        MODEL_REGISTRY_PATH.write_text(json.dumps({"active_model": None, "history": []}, indent=2))
        logging.info("Created model registry at %s", MODEL_REGISTRY_PATH)


def ensure_env_file() -> None:
    if ENV_FILE.exists():
        return
    if ENV_TEMPLATE.exists():
        shutil.copyfile(ENV_TEMPLATE, ENV_FILE)
        logging.info("Created .env from template")
    else:
        ENV_FILE.write_text(
            textwrap.dedent(
                """\
                # Autogenerated environment file
                OLLAMA_BASE_URL=http://127.0.0.1:11434
                OLLAMA_MODEL=llama3
                CREWAI_PORT=8000
                CREWAI_LOG_LEVEL=INFO
                """
            )
        )
        logging.info("Created default .env file")


class VirtualEnvManager:
    """Manage project virtual environment."""

    def __init__(self, target_dir: Path) -> None:
        self.target_dir = target_dir
        self.bin_dir = target_dir / ("Scripts" if platform.system() == "Windows" else "bin")
        self.python = self.bin_dir / ("python.exe" if platform.system() == "Windows" else "python")
        self.pip = self.bin_dir / ("pip.exe" if platform.system() == "Windows" else "pip")

    def exists(self) -> bool:
        return self.python.exists()

    def create(self, *, recreate: bool = False) -> None:
        if recreate and self.target_dir.exists():
            logging.info("Removing existing virtualenv at %s", self.target_dir)
            shutil.rmtree(self.target_dir)
        if self.exists():
            logging.info("Virtual environment already exists at %s", self.target_dir)
            return
        logging.info("Creating virtual environment at %s", self.target_dir)
        builder = EnvBuilder(with_pip=True, upgrade_deps=True)
        builder.create(self.target_dir)

    def install_requirements(self, requirement_files: Iterable[Path]) -> None:
        for req_file in requirement_files:
            if not req_file.exists():
                logging.warning("Requirement file not found: %s", req_file)
                continue
            logging.info("Installing Python dependencies from %s", req_file)
            run([str(self.pip), "install", "--upgrade", "-r", str(req_file)])

    def install_packages(self, packages: Iterable[str]) -> None:
        packages = list(packages)
        if not packages:
            return
        logging.info("Installing Python packages: %s", ", ".join(packages))
        run([str(self.pip), "install", "--upgrade", *packages])


class OllamaInstaller:
    """Install Ollama in a sandboxed directory."""

    DOWNLOAD_MAP: Dict[Tuple[str, str], Dict[str, str]] = {
        ("Linux", "x86_64"): {
            "url": "https://ollama.ai/download/ollama-linux-amd64.tgz",
            "sha": "https://ollama.ai/download/ollama-linux-amd64.tgz.sha256sum",
        },
        ("Linux", "arm64"): {
            "url": "https://ollama.ai/download/ollama-linux-arm64.tgz",
            "sha": "https://ollama.ai/download/ollama-linux-arm64.tgz.sha256sum",
        },
        ("Darwin", "x86_64"): {
            "url": "https://ollama.ai/download/ollama-darwin-amd64.tgz",
            "sha": "https://ollama.ai/download/ollama-darwin-amd64.tgz.sha256sum",
        },
        ("Darwin", "arm64"): {
            "url": "https://ollama.ai/download/ollama-darwin-arm64.tgz",
            "sha": "https://ollama.ai/download/ollama-darwin-arm64.tgz.sha256sum",
        },
    }

    def __init__(self, target_dir: Path) -> None:
        self.target_dir = target_dir
        self.ollama_binary = self.target_dir / "ollama"

    def is_installed(self) -> bool:
        return self.ollama_binary.exists()

    def install(self, *, force: bool = False) -> None:
        system = platform.system()
        machine = platform.machine().lower()

        if system == "Windows":
            self._install_on_windows(force=force)
            return

        arch = "arm64" if "arm" in machine else "x86_64"
        key = (system, arch)
        if key not in self.DOWNLOAD_MAP:
            raise DeployError(f"Ollama installation for {system} ({arch}) is not supported yet.")

        urls = self.DOWNLOAD_MAP[key]
        DOWNLOADS_DIR.mkdir(parents=True, exist_ok=True)
        archive_name = Path(urls["url"]).name
        archive_path = DOWNLOADS_DIR / archive_name

        if not archive_path.exists() or force:
            sha_url = urls["sha"]
            sha_value = self._fetch_sha256(sha_url)
            download(urls["url"], archive_path, expected_sha256=sha_value)

        logging.info("Extracting Ollama binary to %s", self.target_dir)
        self.target_dir.mkdir(parents=True, exist_ok=True)

        with tarfile.open(archive_path, "r:gz") as tar:
            member = next((m for m in tar.getmembers() if m.name.endswith("/ollama") or m.name == "ollama"), None)
            if not member:
                raise DeployError("Downloaded archive does not contain `ollama` binary.")
            member.name = Path(member.name).name  # prevent directory traversal
            tar.extract(member, path=self.target_dir)

        os.chmod(self.ollama_binary, os.stat(self.ollama_binary).st_mode | stat.S_IEXEC)
        logging.info("Ollama installed at %s", self.ollama_binary)

    def _fetch_sha256(self, url: str) -> str:
        logging.debug("Fetching expected SHA256 from %s", url)
        try:
            with urlopen(url) as response:
                payload = response.read().decode("utf-8").strip()
        except (HTTPError, URLError) as exc:
            raise DeployError(f"Unable to fetch checksum from {url}: {exc}") from exc
        # Format: '<hash>  filename'
        return payload.split()[0]

    def _install_on_windows(self, *, force: bool) -> None:
        """Attempt to install Ollama on Windows via winget fallback."""
        if self.is_installed() and not force:
            logging.info("Ollama binary already present at %s", self.ollama_binary)
            return

        logging.info("Attempting Ollama installation via winget")
        try:
            run(["winget", "install", "--id", "Ollama.Ollama", "--silent"], check=True)
        except DeployError as exc:
            raise DeployError(
                "Failed to install Ollama via winget. Install Ollama manually and re-run the deploy script."
            ) from exc

        # Attempt to locate the installed binary
        candidate_paths = [
            Path(os.getenv("ProgramFiles", "")) / "Ollama" / "ollama.exe",
            Path(os.getenv("ProgramFiles(x86)", "")) / "Ollama" / "ollama.exe",
        ]
        for candidate in candidate_paths:
            if candidate.exists():
                self.target_dir.mkdir(parents=True, exist_ok=True)
                shutil.copy(candidate, self.ollama_binary)
                logging.info("Copied Ollama executable to %s", self.ollama_binary)
                return
        raise DeployError("Ollama installation succeeded but the binary could not be located automatically.")


class CrewCtlInstaller:
    """Install the crewctl CLI into the virtual environment."""

    def __init__(self, venv: VirtualEnvManager) -> None:
        self.venv = venv

    def install(self) -> None:
        python_path = self.venv.python
        run([str(python_path), "-m", "pip", "install", "--upgrade", "pip", "wheel", "setuptools"])
        # Install project in editable mode to expose crewctl package.
        run([str(python_path), "-m", "pip", "install", "-e", str(ROOT)])
        self._create_launcher()

    def _create_launcher(self) -> None:
        launcher_dir = self.venv.bin_dir
        launcher_dir.mkdir(parents=True, exist_ok=True)
        python_path = self.venv.python

        launcher_script = launcher_dir / ("crewctl" if platform.system() != "Windows" else "crewctl.cmd")
        if platform.system() == "Windows":
            content = textwrap.dedent(
                f"""\
                @echo off
                set PYTHONPATH={ROOT}
                set CREWCTL_ROOT={ROOT}
                "{python_path}" -m crewctl %*
                """
            )
        else:
            content = textwrap.dedent(
                f"""\
                #!/usr/bin/env bash
                export PYTHONPATH="{ROOT}"
                export CREWCTL_ROOT="{ROOT}"
                exec "{python_path}" -m crewctl "$@"
                """
            )
        launcher_script.write_text(content)
        os.chmod(launcher_script, os.stat(launcher_script).st_mode | stat.S_IEXEC)
        logging.info("Installed crewctl launcher at %s", launcher_script)


def determine_requirement_files(with_training: bool) -> Iterable[Path]:
    files = [ROOT / "requirements.txt"]
    deploy_req = ROOT / "requirements-deploy.txt"
    if deploy_req.exists():
        files.append(deploy_req)
    if with_training:
        training_req = ROOT / "requirements-train.txt"
        if training_req.exists():
            files.append(training_req)
        else:
            logging.warning("Training requirements requested but %s not found", training_req)
    return files


def ensure_secure_permissions() -> None:
    if platform.system() == "Windows":
        return
    for path in [STATE_DIR, BIN_DIR, LOG_DIR]:
        if path.exists():
            os.chmod(path, 0o750)
    if ENV_FILE.exists():
        os.chmod(ENV_FILE, 0o640)


def parse_args(argv: Optional[Iterable[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Deploy CrewAI + Ollama stack.")
    parser.add_argument(
        "--force",
        action="store_true",
        help="Reinstall components even if they already exist.",
    )
    parser.add_argument(
        "--with-training-extras",
        action="store_true",
        help="Install additional dependencies required for model pre-training / LoRA.",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Enable verbose logging.",
    )
    parser.add_argument(
        "--non-interactive",
        action="store_true",
        help="Run without interactive prompts.",
    )
    return parser.parse_args(argv)


def check_prerequisites(non_interactive: bool) -> None:
    logging.info("Checking system prerequisites")

    if sys.version_info < (3, 10):
        raise DeployError("Python 3.10 or newer is required.")

    required_bins = ["git", "curl"]
    if platform.system() != "Windows":
        required_bins.append("tar")
    missing = [tool for tool in required_bins if shutil.which(tool) is None]
    if missing:
        raise DeployError(f"Missing required system tools: {', '.join(missing)}")

    if not non_interactive:
        logging.info("System prerequisites satisfied.")


def summarize(python_path: Path, ollama_path: Path) -> None:
    logging.info(
        "\nDeployment summary:\n"
        "  CrewAI root            : %s\n"
        "  Virtual environment    : %s\n"
        "  Python interpreter     : %s\n"
        "  crewctl launcher       : %s\n"
        "  Ollama binary          : %s\n"
        "  Model registry         : %s\n"
        "  Environment file       : %s\n",
        ROOT,
        python_path.parent.parent,
        python_path,
        python_path.parent / ("crewctl" if platform.system() != "Windows" else "crewctl.cmd"),
        ollama_path,
        MODEL_REGISTRY_PATH,
        ENV_FILE,
    )


def main(argv: Optional[Iterable[str]] = None) -> int:
    args = parse_args(argv)
    setup_logging(verbose=args.verbose)

    logging.info("Starting CrewAI + Ollama deployment")
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    ensure_model_registry()
    ensure_env_file()

    try:
        check_prerequisites(args.non_interactive)

        venv_dir = STATE_DIR / "venv"
        venv_manager = VirtualEnvManager(venv_dir)
        venv_manager.create(recreate=args.force)
        requirement_files = determine_requirement_files(args.with_training_extras)
        venv_manager.install_requirements(requirement_files)

        crewctl_installer = CrewCtlInstaller(venv_manager)
        crewctl_installer.install()

        ollama_installer = OllamaInstaller(BIN_DIR)
        ollama_installer.install(force=args.force)

        ensure_secure_permissions()
        summarize(venv_manager.python, ollama_installer.ollama_binary)
        logging.info(
            "Deployment complete. Use `%s` to manage the stack.",
            crewctl_installer.venv.bin_dir
            / ("crewctl" if platform.system() != "Windows" else "crewctl.cmd"),
        )

    except DeployError as exc:
        logging.error("Deployment failed: %s", exc)
        return 1
    except Exception as exc:  # pragma: no cover - unexpected exceptions
        logging.exception("Unexpected error during deployment: %s", exc)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
